spring.application.name=OrderService


server.servlet.context-path=/api/v1
server.port=9020


spring.datasource.url=jdbc:postgresql://localhost:5432/OrderService
spring.datasource.username=sumanbaral
spring.datasource.password=suman12345
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql